### ISSUE TITLE
Tango initialization error

### ISSUE THREAD

**Issue by tahmidmozaffar** [dannyyy/GoogleProjectTangoBinding#1]
Hello, I just open a xamarin.android project, add GoogleProjectTangoBinding from nuget package. Then in OnCreate I call 

`Tango mTango = new Tango(this);`

If shows runtime exception with this message...

> Java.Lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.infolytx.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.infolytx.test-1/lib/x86, /data/app/com.infolytx.test-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libtango_client_api.so

**Comment by tahmidmozaffar** [comment]
Ok... So I was making a mistake... trying to run the app in simulator. Very silly mistake. Sorry for that. I am closing the issue.

**Comment by gleblebedev** [comment]
Hi,

I have the same issue. I'm running it on Lenovo Phab2 Pro. The issue is the same:

ava.Lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/GoogleProjectTangoExample.GoogleProjectTangoExample-1/base.apk"],nativeLibraryDirectories=[/data/app/GoogleProjectTangoExample.GoogleProjectTangoExample-1/lib/arm64, /data/app/GoogleProjectTangoExample.GoogleProjectTangoExample-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libtango_client_api.so"
